- README.md
let's see how fast it goes, otherwise I can spin up more droplets :smile:
> Add thaJeztah to readme

- README.md
Signed-off-by: Nigel <nigelpoulton@hotmail.com>
> Adding 20 nodes from @nigelpoulton

- README.md
I have @nigelpoulton branch as base to avoid conflicts, that's why you see both commits here.
Great idea @chanwit!
> Add 20 nodes from @akalipetis

- README.md
> Tough iq 3nodes

- README.md
5 is a much nicer number than 3.
> increased from 3 to 5 nodes

- README.md
Our interactive environment will be able to join the cluster https://www.katacoda.com/courses/docker-orchestration/playground 
At the time we can automate the environments / joining nodes from our end. At Dockercon EU we had ~100 swarm node as an example.
> Katacoda.com environments can join the cluster

- README.md
Thank you @everett-toews from Rackspace for this 100 nodes.
> Rackspace contribution for 100 node (override PR #15)

- README.md
> Small contribution

- README.md
As we're always using Docker on a Raspberry Pi it's easy to contribute the right number of nodes. 😏  🐳 
Signed-off-by: Dieter Reuter <dieter.reuter@me.com>
> Add 314 DO nodes from Hypriot

- README.md
So happy this is even during UTC daytime!
> Add some more nodes :)

- digital-ocean/create-swarm2k-nodes-do.sh
- digital-ocean/ssh-command-do.sh
These are some examples how to create and ramp up some nodes on Digital Ocean in different data centers.
Signed-off-by: Dieter Reuter <dieter.reuter@me.com>
> Add some script to create/manage DO nodes

- README.md
I just added, for the record, my company info
> Added company info

- README.md
claimed my 5 nodes.
Thanks or this event.
> claimed 5 nodes for @toughIQ

- README.md
Signed-off-by: Dieter Reuter <dieter.reuter@me.com>
> Add Twitter handle Quintus23M

- README.md
> add the name AR-BRO

- README.md
> add neverlock's twitterID

- README.md
Second attempt. Now looks better =)
> Claimed 12 nodes for @AlexPostID

- README.md
ping @chanwit there you go :smile:
> claim thaJeztah nodes

- README.md
- amazonec2/README.md
- amazonec2/create-machines.sh
- amazonec2/join_swarm2k.yml
- amazonec2/run.sh
Fabrizio added himself to the hall of fame :)
> Claim fsoppelsa

- README.md
Proud to have been part of this adventure.
> tillersystems.com nodes

- README.md
> Adding swarm2k2 + swarm2kae

- README.md
> claim nodes
